mod even_or_odd;
mod opposites_attract;
mod beginner_series;
mod sum_of_positive;
mod string_repeat;
mod calculate_bmi;
mod fake_binary;
mod terminal_game;
mod personalized_message;
mod calculate_average;
mod square_every_digit;

pub use even_or_odd::even_or_odd_mod;
pub use opposites_attract::opposites_attract_mod;
pub use beginner_series::beginner_series_mod;
pub use sum_of_positive::sum_of_positive_mod;
pub use string_repeat::string_repeat_mod;
pub use calculate_bmi::calculate_bmi_mod;
pub use fake_binary::fake_binary_mod;
pub use terminal_game::terminal_game_mod;
pub use personalized_message::personalized_message_mod;
pub use calculate_average::find_average_mod;
pub use square_every_digit::square_every_digit_mod;